
server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: utf-8
      enabled: true





ip: localhost
socketPort: 5053
dockingUrl: https://pm.smartsuite.co.kr:4102/device/test/docking
statusUpdateUrl: https://pm.smartsuite.co.kr:4102/device/test/statupdate

#stationId: 1  임의로 지정